### ISSUE TITLE
MPI primitives

### ISSUE THREAD

**Issue by dionhaefner** [PhilipVinc/mpi4jax#1]
This is a list of everything that's supported by `mpi4py`:

- Abort
- Accept
- Allgather
- Allgatherv
- Allreduce
- Alltoall
- Alltoallv
- Alltoallw
- Barrier
- Bcast
- Bsend
- Bsend_init
- Call_errhandler
- Cart_map
- Clone
- Compare
- Connect
- Create
- Create_cart
- Create_dist_graph
- Create_dist_graph_adjacent
- Create_graph
- Create_group
- Create_intercomm
- Create_keyval
- Delete_attr
- Disconnect
- Dup
- Dup_with_info
- Exscan
- Free
- Free_keyval
- Gather
- Gatherv
- Get_attr
- Get_errhandler
- Get_group
- Get_info
- Get_name
- Get_parent
- Get_rank
- Get_size
- Get_topology
- Graph_map
- Iallgather
- Iallgatherv
- Iallreduce
- Ialltoall
- Ialltoallv
- Ialltoallw
- Ibarrier
- Ibcast
- Ibsend
- Idup
- Iexscan
- Igather
- Igatherv
- Improbe
- Iprobe
- Irecv
- Ireduce
- Ireduce_scatter
- Ireduce_scatter_block
- Irsend
- Is_inter
- Is_intra
- Iscan
- Iscatter
- Iscatterv
- Isend
- Issend
- Join
- Mprobe
- Probe
- Recv
- Recv_init
- Reduce
- Reduce_scatter
- Reduce_scatter_block
- Rsend
- Rsend_init
- Scan
- Scatter
- Scatterv
- Send
- Send_init
- Sendrecv
- Sendrecv_replace
- Set_attr
- Set_errhandler
- Set_info
- Set_name
- Spawn
- Spawn_multiple
- Split
- Split_type
- Ssend
- Ssend_init

(plus lower-case variants to communicate Python objects)

#### Thoughts:

- Non-blocking operations (e.g. `Isend`) are perhaps out of scope for now, since I don't see a way to transparently hand back the request object to Python. I guess you could do it C-style and hand back a raw pointer if you really want to support non-blocking ops.
- Lower-case operations (e.g. `send`) seem cumbersome to implement and not that useful from JITed code.

I would suggest the following minimal list to start out with:

- Abort
- Allgather
- Allreduce
- Alltoall
- Barrier
- Bcast
- Disconnect
- Gather
- Get_rank
- Get_size
- Recv
- Reduce
- Scan
- Scatter
- Send
- Sendrecv
- Spawn
- Split

I could probably contribute some of those if you agree.

**Comment by PhilipVinc** [comment]
lower case operations are more or less equivalent to the upper-case ones but operate on arbitrary python objects, so I agree that they are out of scope.

In general, I'd aim just to cover what's useful, and not everything.
For example, assuming communicators are static objects that won't be created in jitted functions which is what is assumed now, we can also drop

- Get_rank
- Get_size
- disconnect
 - spawn 
- split
- abort

If you or anyone actually need those, however, I'm open to contributions.

I think that for now the most important things to get working are
Send/Recv/Scatter/Barrier/Bcast/gather/allgather kind of things. 

Also, a mechanism to get the correct adjoint/gradient of reduction operations would be nice.

**Comment by dionhaefner** [comment]
Good point on all communicators being static by design. I do have a use case where I use `split` to do a reduction over a subset of all processes, but I guess one can always create these subcommunicators ahead of time. Otherwise, creating a new communicator would trigger a recompile every time I guess.

So the new minimal list of primitives is this:

- [ ] Allgather
- [ ] Allreduce
- [ ] Alltoall
- [ ] Barrier
- [ ] Bcast
- [ ] Gather
- [ ] Recv
- [ ] Reduce
- [ ] Scan
- [ ] Scatter
- [ ] Send
- [ ] Sendrecv

**Comment by PhilipVinc** [comment]
Yes.
At least, that's how we are dealing with it currently: the communicator is a keyword argument (so you can only treat it as a jitting constant).

**Comment by GallagherCommaJack** [comment]
what happened to `reduce_scatter`? seems like it's still not implemented, and it's a pretty useful op for eg efficient implementation of zero2 weight sharding.

**Comment by dionhaefner** [comment]
PRs welcome! :)

Should be very similar to `scatter` so you could use that as a template.
