### ISSUE TITLE
Release and auto-install dependencies

### ISSUE THREAD

**Issue by PhilipVinc** [PhilipVinc/mpi4jax#13]
Our `setup.py` requires `mpi4py` to be already installed to run.

If one clones the repo, the `pyproject.toml` specifies this dependency and therefore if someone does `pip install /path/to/mpi4jax` pip correctly finds the pyproject, installs the dependencies and THEN runs `setup.py`. All is good.

As far as I understand, there are 2 ways one can distribute packages on PyPi/pip: Source distributions (sdist) and Wheels/binary distributions (bdist).

Binary Distributions (wheels) will build the Cython module on the host computer, and then upload to PyPi a package with the precompiled binary dependency. As much as this is handy, since we compile and dynamically link to the MPI headers/Library, of which there are a bunch of different distributions, we cannot really do this (unless I'm wrong?).

Maybe there is a workaround to compile something on target's machine, but I am not aware of it...

This leaves us to source distributions, which as far as I read online will be deprecated in the future.
Source distributions mostly include source files + setup.py, but do not include `pyproject.toml`, so releases (like the last v0.2.1) will not be able to install mpi4py before running setup.py. The workaround is evidently to install it before installing mpmi4jax, but that is... ugly? 

Isn't there a way to include the pyproject.toml in a source distribution?  Because right now in a pristine environment, `pip install mpi4jax` will fail unless one runs `pip install mpi4py` beforehand.

@dionhaefner do you have any insights?

**Comment by dionhaefner** [comment]
As you observe we cannot supply wheels, but I don't know why you think that `pyproject.toml` is not part of a source distribution. If I run `python setup.py sdist` in the `mpi4jax` root folder, `pyproject.toml` is included in the resulting tarball (but indeed not in the tarball that you uploaded to PyPI).

If that doesn't work, the usual pattern is to tell users to install the build dependencies first, like `mpi4py` does. I don't think this is ugly, it just needs to be documented.

**Comment by PhilipVinc** [comment]
But that's what I did:
I run
```python 
cd ../path/to/mpi4jax
python setup.py sdist
twine upload dist/*
```

And If I check in the generated tarball there is no pyproject.toml...

**Comment by dionhaefner** [comment]
Maybe this is a `pip` or `setuptools` version issue? Definitely works for me.

Otherwise, you can decide what you want to include in a source distribution via the `MANIFEST.in` file.

Official docs: https://packaging.python.org/guides/using-manifest-in/

**Comment by dionhaefner** [comment]
According to that document, you need `setuptools >= 43.0.0` for `pyproject.toml` to be included.

**Comment by PhilipVinc** [comment]
I had 42.0.0. I just tried and with the updated version it works

**Comment by PhilipVinc** [comment]
About the [Cython stuff](https://github.com/PhilipVinc/mpi4jax/commit/16e9a2f2d128b513b2924f2a9d0f969b020dec3b#commitcomment-42290484), 

Once `pyproject.toml` is fixed, I can assume that Cython is always present and revert that commit, right?

**Comment by dionhaefner** [comment]
Yes, that should work

**Comment by PhilipVinc** [comment]
Apparently, `pyproject` will auto-install Cython but not mpi4py, for some reason unknown to me.

**Comment by dionhaefner** [comment]
Could be because mpi4py is only available as a source distribution?

**Comment by PhilipVinc** [comment]
And another problem is that (for unknown reasons) the GitHub action responsible for uploading to pypi does not put in the sdist the `.pyx` files...

**Comment by dionhaefner** [comment]
Should we just supply a `MANIFEST.in` file? Then we wouldn't be dependent on setuptools versions or anything.

**Comment by PhilipVinc** [comment]
Yeah, that’s also what I realised could solve all problems.
I think I’ll go down that way.
Il 15 set 2020, 13:38 +0200, Dion Häfner <notifications@github.com>, ha scritto:
