### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by dionhaefner** [PhilipVinc/mpi4jax#14]
It would be nice if you could add a code coverage badge to see what else needs testing, and whether there is any dead code.

**Comment by PhilipVinc** [comment]
I'll try to do this later today or tomorrow.

BTW, how does code coverage for the Cython file work? is it automatic?

**Comment by dionhaefner** [comment]
I don't think we can get coverage for Cython.

**Comment by dionhaefner** [comment]
[I stand corrected](http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html), but it might take some fiddling to get this set up.
