### ISSUE TITLE
Deadlock when Python exits before kernel executes

### ISSUE THREAD

**Issue by dionhaefner** [PhilipVinc/mpi4jax#22]
This one's a bit tricky to reproduce, but I've seen deadlocks in cases where this was the whole script:

```python
import jax
jax.config.enable_omnistaging()
import jax.numpy as jnp

from mpi4py import MPI
from mpi4jax import Send

comm = MPI.COMM_WORLD
assert comm.Get_size() == 1

# send to non-existing rank
jax.jit(lambda x: Send(x, dest=100, comm=comm))(
    jnp.ones(10)
)
```

This should throw an error, but deadlocks instead. I think this is because Python exits before the JITed function has a chance to run (because everything is asynchronous in JAX), so `MPI_Finalize` is called (at interpreter exit) before the `MPI_Send`.

If there is a way in JAX to force synchronization of all pending XLA operations we could register that as an `atexit` handler that runs *before* `MPI_Finalize`.

**Comment by PhilipVinc** [comment]
Yes, I experienced the same thing over on netket.
I resorted to calling [‘block_until_ready()’](https://jax.readthedocs.io/en/latest/async_dispatch.html).

Registering it as an eye it seems a nice idea.
Il 18 set 2020, 11:18 +0200, Dion Häfner <notifications@github.com>, ha scritto:

**Comment by dionhaefner** [comment]
`block_until_ready` doesn't work on tokens though, so there is no way to block a Send call 😕

**Comment by PhilipVinc** [comment]
In theory printing the token should force Jax to flush the command queue?

At least, it works for arrays.

Maybe we could print it to /dev/null or convert it to a python type, if that is possible?

**Comment by dionhaefner** [comment]
Printing is not enough either. `time.sleep(1)` before exiting is the only thing I have found working in this case. I'm opening an issue at JAX.

**Comment by PhilipVinc** [comment]
And I suspect sleep won't be enough either in all cases...
Nothing is forcing Jax to execute the code, I think.

Thanks for opening the issue.

**Comment by dionhaefner** [comment]
Yes, sleep is just a hacky workaround.

https://github.com/google/jax/issues/4335
