### ISSUE TITLE
support for broadcast?

### ISSUE THREAD

**Issue by romanodev** [PhilipVinc/mpi4jax#26]
Great project! Is there any plan to support Broadcast?

**Comment by dionhaefner** [comment]
Yes! See https://github.com/PhilipVinc/mpi4jax/issues/1#issuecomment-662369898

It should be easy enough to add, so you're welcome to have a stab at it if you want to contribute. Otherwise you can say pretty please and I might do it :wink:

**Comment by romanodev** [comment]
Great. Now I am focusing on releasing a package that makes use of mpi4py. I will check back after that (roughly a few weeks) and, if not supported yet, I will have a stab at it.
