### ISSUE TITLE
Maybe remove direct dependency on jaxlib?

### ISSUE THREAD

**Issue by PhilipVinc** [PhilipVinc/mpi4jax#33]
Jax does not depend on jaxlib.
It is not entirely clear to me why. 

I guess that it's because you want to be able to switch jaxlib version with/without CUDA support,
but our direct dependency should not hinder that, or does it?

**Comment by dionhaefner** [comment]
I guess this is because they want people to make a conscious choice which jaxlib they choose? I don't see why we can't depend on jaxlib, but if you prefer to be consistent we could also do a runtime check instead (we need the minimum version for the `has_side_effects` argument to `CustomCall`).
