### ISSUE TITLE
Find out which JAX versions work

### ISSUE THREAD

**Issue by dionhaefner** [PhilipVinc/mpi4jax#45]

**Comment by PhilipVinc** [comment]
Mpi4jax version: '0.2.10'

- jax==0.2.9, jaxlib==0.1.61+cuda111   ❌
- jax==0.2.9, jaxlib==0.1.60+cuda111   ❌
- jax==0.2.9, jaxlib==0.1.59+cuda111   ❌
- jax==0.2.8, jaxlib==0.1.58+cuda111   ❌
```
RuntimeError: Internal: Unexpected shape kind for %after-all.3 = token[] after-all(), metadata={op_type="create_token" op_name="jit(<lambda>)/create_token" source_file="/home/filippovicentini/Dropbox/Ricerca/Codes/Python/mpi4jax/mpi4jax/collective_ops/allreduce.py" source_line=62} and shape index {}
```
- jax==0.2.8, jaxlib==0.1.57+cuda111   ❌✔️
- jax==0.2.8, jaxlib==0.1.56+cuda111   ❌✔️
(Less tests fail. Core tests pass):
```
test_deadlock_on_exit
E           subprocess.TimeoutExpired: Command '['/home/filippovicentini/Documents/pythonenvs/mpi4jax_env/bin/python3.8', PosixPath('/tmp/pytest-of-filippovicentini/pytest-5/test_deadlock_on_exit0/deadlock_on_exit.py')]' timed out after 10 seconds

test_allreduce_vjp
>       res, vjp_fun = jax.vjp(lambda x: Allreduce(x, op=MPI.SUM)[0], arr)
E     NotImplementedError: must override

../../../../../Documents/pythonenvs/mpi4jax_env/lib64/python3.8/site-packages/jax/core.py:803: NotImplementedError
```

**Comment by dionhaefner** [comment]
:+1:

I wonder how we should constrain the `jaxlib` version. Putting it in `setup.py` could be awkward because it could auto-install the CPU version instead (this is connected to #33). Maybe a runtime check *is* the way to go...

**Comment by PhilipVinc** [comment]
Runtime check i think ? 
Also it makes it easy to experiment with different versions...

**Comment by PhilipVinc** [comment]
So, as the issue seems fixed and basically there is no prior version of jaxlib where there are no issues, I propose that if the next release works well (0.1.62) we could require that as a minimum version? 
Or, since cpu works just fine, we could raise a warning saying that everything is broken if we detect a gpu? 

I'd go with option 1, personally.

**Comment by dionhaefner** [comment]
I would propose a middle ground: `jaxlib>=0.1.55,!=0.1.58,!=0.1.59,!=0.1.60,!=0.1.61`

As it see it, with the JAX ecosystem being as volatile as it is, there will always be versions that break our code. So we might as well start excluding versions now.

**Comment by PhilipVinc** [comment]
yeah, but tests are half broken also on 1.56/57, while they work fine on >=1.58 if you only consider CPU

**Comment by dionhaefner** [comment]
You mean the `test_allreduce_vjp`? Is that our fault or a `jaxlib` bug?

**Comment by PhilipVinc** [comment]
`jaxlib`

**Comment by dionhaefner** [comment]
I see. Then I agree to require the next release, since it's the only one that supports everything we do.
