### ISSUE TITLE
Cannot operate on NumPy arrays

### ISSUE THREAD

**Issue by dionhaefner** [PhilipVinc/mpi4jax#5]
The non-JIT version of each primitive should probably work on non-JAX arrays, too. This should be easy enough to do.

Current error message:

```python
AttributeError: 'numpy.ndarray' object has no attribute 'device_buffer'
```

**Comment by PhilipVinc** [comment]
we could use `jax.numpy.asarray` on every input ? 
However, scalars would get converted to 0-dim arrays, which I think it's fine from the jax point of view (most jaw operations convert non-jax types to jax types).

Do you agree?

**Comment by PhilipVinc** [comment]
Yeah, I think the culprit is that for some reason in [mpi4jax/collective_ops/allreduce.py:38](https://github.com/PhilipVinc/mpi4jax/blob/989237be3fc7acd26bbd1f18ce737f90b055517e/mpi4jax/collective_ops/allreduce.py#L38) I use `numpy.asarray` instead of `jax.numpy.asarray`.
