### ISSUE TITLE
Use lowercase names for communication primitives!

### ISSUE THREAD

**Issue by dionhaefner** [PhilipVinc/mpi4jax#54]
We copied the primitive names from `mpi4py`, but since we don't have the same API, wouldn't it make sense to be more Pythonic and user lower-case function names instead?

I.e., `mpi4jax.send(...)` instead of `mpi4jax.Send(...)`.

**Comment by PhilipVinc** [comment]
I agree.

**Comment by PhilipVinc** [comment]
Proposal: rename the functions to lowercase, keep around the old function name with a deprecation warning, release a v0.3.0 and a month later remove the deprecated methods.

**Comment by dionhaefner** [comment]
Yes, fine with me. I can do this as part of #55.
