### ISSUE TITLE
Respecting GPU Stream

### ISSUE THREAD

**Issue by PhilipVinc** [PhilipVinc/mpi4jax#60]
Customcalls on gpu are passed a stream object in order to perform operations asynchronously.
Essentially they are supposed to enqueue operations to an operation buffer.

So we could assume that previous operations are also enqueued to the stream and not necessarily completed.

But our GPU operations do not respect this, and execute Syncronously (immediately), without checking that the stream of previous operations is empty.
I don't know if that is safe or not...

I believe that we should investigate whever we should change the code of `MPI_Allreduce` and similar to be more like
```python

cdef void mpi_allreduce(cudaStream_t* stream, void** buffers,
                        const char* opaque, size_t opaque_len) nogil except *:

    if COPY_TO_HOST:
        checked_cuda_memcpyAsync(in_buf, data, count, cudaMemcpyDeviceToHost, stream)

    cudaStreamSynchronize(stream)
    mpi_xla_bridge.mpi_allreduce(in_buf, out_buf, nitems, dtype, op, comm, token)

    if COPY_TO_HOST:
        # copy back to device
        checked_cuda_memcpy(out_data, out_buf, count, cudaMemcpyHostToDevice)
```

where the latter operation could be async, but then we need a callback (CudaEvent) to deallocate the cpu buffer when the memcpy is completed.

Also see https://on-demand.gputechconf.com/gtc/2014/presentations/S4236-multi-gpu-programming-mpi.pdf

However I'm not sure this is really needed. I never noticed data corruption so...

**Comment by dionhaefner** [comment]
> So we could assume that previous operations are also enqueued to the stream and not necessarily completed.

This is what the newly introduced `cudaStreamSynchronize` takes care of. I assumed that a synchronous operation implicitly flushes the stream.

So we could also move the sync before the `memcpy` if that eases your mind :)

**Comment by PhilipVinc** [comment]
Ah, I was on a stale branch, I had noticed the code when reviewing but now I couldn't see it anymore...

I'm not sure it always does. I believe it implicitly flushes the default stream, which incidentally is what XLA usually uses. 
But they might change it at some point.

I think we can either enqueue our operation as async, and then flush, maybe this has smaller overhead?
I'm not sure..

**Comment by dionhaefner** [comment]
I wouldn't bother with async. This just makes everything more complicated for little to no performance gain, since the MPI operations are synchronous anyway. If you're worried about this, let's just move the synchronization up a few lines.

**Comment by PhilipVinc** [comment]
By the way, that is unrelated, but have you ever seen crashes such as https://gist.github.com/PhilipVinc/da770128e626a0c623f4a1db2cd4d806 when calling CUDA functions?

**Comment by dionhaefner** [comment]
Not this particular one, but I've seen many crashes (usually because I messed up some shapes or didn't pass the correct tokens).
