### ISSUE TITLE
version issues

### ISSUE THREAD

**Issue by PhilipVinc** [PhilipVinc/mpi4jax#63]
I think there are still issues with declaring our version.
I just noticed the following:

If you install mpi4jax from conda, pip cannot determine the version of mpi4jax.
This creates problems because if you have a package depending on mpi4jax installed through pip, he will attempt to reinstall mpi4jax (Eventually wreaking havoc because of mpi)

**Comment by PhilipVinc** [comment]
Noticed while using the environment file:

environment.yml
```python
name: netket_env
channels:
 - numba
 - defaults
 - conda-forge
dependencies:
 - python>=3.8
 - numpy>=1.20
 - scipy>=1.5.2
 - networkx
 - mpi4jax>=0.2.11
 - tqdm
 - pip
 - matplotlib
 - openmpi
 - mpi4py
 - mkl
 - numba
 - dm-tree
```

```bash
conda env create -f environment.yml
conda activate netket_env
git clone https://github.com/netket/netket
cd netket
pip install .[mpi]
```

**Comment by PhilipVinc** [comment]
Indeed, going into
```
/Users/filippovicentini/anaconda3/envs/netket_env_test/lib/python3.9/site-packages
```

I see for example the folder
```
mpi4py
mpi4py-3.0.3.dist-info
mpi4jax
mpi4jax-0.0.0.dist-info
```

and the file
```
$ head mpi4py-3.0.3.dist-info/METADATA

Metadata-Version: 2.1
Name: mpi4py
Version: 3.0.3
```

while
```
$ head mpi4jax-0.0.0.dist-info/METADATA

Metadata-Version: 2.1
Name: mpi4jax
Version: 0.0.0
```

**Comment by PhilipVinc** [comment]
@dionhaefner 
```python
mpi4jax on  master [$] via netket_env via 🅒 netket_env_test via 🐍 3.8.7
➜ python setup.py --version
Compiling mpi4jax/_src/xla_bridge/mpi_xla_bridge.pyx because it changed.
Compiling mpi4jax/_src/xla_bridge/mpi_xla_bridge_cpu.pyx because it changed.
[1/2] Cythonizing mpi4jax/_src/xla_bridge/mpi_xla_bridge.pyx
[2/2] Cythonizing mpi4jax/_src/xla_bridge/mpi_xla_bridge_cpu.pyx
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
0.0.0
(netket_env_test)
```

**Comment by dionhaefner** [comment]
This should be fixed in #62, because `setuptools_scm` is now a requirement to even run `setup.py`. Previously, you could do `python setup.py sdist` without having `setuptools_scm`, which results in `0.0.0`. Now, you will get an exception instead.

**Comment by dionhaefner** [comment]
(In case you wonder, yes, I think `setuptools_scm` is a hot mess, especially when combined with `pyproject.toml` build isolation.)

**Comment by dionhaefner** [comment]
Should we ditch `setuptools_scm` and just go with `versioneer` instead?

https://github.com/python-versioneer/python-versioneer

Versioneer is an older tool and requires a `setup.cfg` file. But I've never seen it fail, whereas `setuptools_scm` is just so brittle.

**Comment by PhilipVinc** [comment]
FYI: the problem was that we did not have setuptools_scm on Conda-forge recipe installeed.

**Comment by PhilipVinc** [comment]
no, it's still not fixed in conda...

**Comment by dionhaefner** [comment]
Let's make the switch. This will just take a minute.

**Comment by PhilipVinc** [comment]
ok

**Comment by dionhaefner** [comment]
Mmmh, now the `pyx` files are not included in `sdist` anymore, so `pip install mpi4jax` from PyPI fails... I'll look into it

**Comment by PhilipVinc** [comment]
Finally, this is addressed.
