### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by dionhaefner** [PhilipVinc/mpi4jax#7]
We cannot raise Python exceptions from our custom XLA calls, so we need some other mechanism to tell users when an MPI exception occurred.

I see a couple of different ways forward:

1. Do a hard abort with a message to `stderr` whenever an MPI function returns an error code (probably best combined with a call to `MPI_Abort`)
2. Return the error code and let the user code handle it

Not sure how useful 2 is though, since you can't raise from jitted code.

**Comment by PhilipVinc** [comment]
I'd vote for option 1
