### ISSUE TITLE
Use Cython wrappers even in non-JIT code?

### ISSUE THREAD

**Issue by dionhaefner** [PhilipVinc/mpi4jax#9]
Currently we implement every primitive twice, once via `mpi4py` for use in non-jitted code, and once via Cython for jitted code. Instead, we could also replace the non-jit implementations with

```python
def send_impl(*args, **kwargs):
    return xla.apply_primitive(send_p, *args, **kwargs)
```

which would then always apply our Cython implementation.

#### Pro:
- Less code to maintain
- Consistent logging and debugging behavior (with `MPI4JAX_DEBUG`)
- Consistent user experience regarding array types and validation

#### Con:
- Our wrappers are more rudimentary than `mpi4py`s with less validation and limited errors
- No way to use `mpi4jax` without the Cython extensions

**Comment by PhilipVinc** [comment]
> Pro:
> - Less code to maintain
> - Consistent logging and debugging behavior (with MPI4JAX_DEBUG)
> - Consistent user experience regarding array types and validation

I agree with that. Less code is particularly nice and makes maintaining easier. 

>Con:
> - Our wrappers are more rudimentary than mpi4pys with less validation and limited errors

I agree. 
> - No way to use mpi4jax without the Cython extensions

What do you mean?

I would also add another con: In theory jitted code has a few more limitations, that non jitted code must not necessarily satisfy. I guess in loops, for example...

However, it is also true that the use case of mpi4jax is jitting code so one might argue that in that case one might simply use mpi4py.

**Comment by dionhaefner** [comment]
> What do you mean?

If we have a separate pure Python implementation then one could use that even if the Cython extensions fail to build. But as you say one could just use `mpi4py` directly in this case. So it's a very minor con at best.

> I would also add another con: In theory jitted code has a few more limitations, that non jitted code must not necessarily satisfy. I guess in loops, for example...

I don't quite understand. Using our Cython wrappers like this doesn't mean that the code is being jitted.

> However, it is also true that the use case of mpi4jax is jitting code so one might argue that in that case one might simply use mpi4py.

Excellent point.

As you observe, implementing this would also fix #5.

**Comment by PhilipVinc** [comment]
> I don't quite understand. Using our Cython wrappers like this doesn't mean that the code is being jitted.

No, ok, you are right.

#5 is now fixed anyway, however this would surely be a nicer way to fix it.

--

I would argue that mpi4jax, as the name says exists solely for jitting MPI code. That way we can also assume The Cython module as a dependency, and go down the path you proposed.

**Comment by dionhaefner** [comment]
:+1: Let's do this.

**Comment by PhilipVinc** [comment]
I was playing around with 
```python
def mpi_allreduce_impl(x, token, op, comm):
    return xla.apply_primitive(mpi_allreduce_p, token, op=op, comm=comm)
```

and it errors with

```phyhon
    def apply_primitive(prim, *args, **params):
      """Impl rule that compiles and runs a single primitive 'prim' using XLA."""
>     compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args), **params)
E     TypeError: unhashable type: 'mpi4py.MPI.Op'
```

I guess we must first encode the types

**Comment by dionhaefner** [comment]
Yes I noticed the same thing. Subclassing `MPI.Op` with `type('hashable_op', (MPI.Op,), dict(__hash__=lambda self: id(self))` works, but seems unnecessarily complicated. I'll open an issue in JAX and see if they have a recommendation.

**Comment by dionhaefner** [comment]
I raised an issue here: https://github.com/google/jax/issues/4280
